### PR TITLE
Add parameter to not set popup at top

### PR DESCRIPTION
**Pull request by GuillaumeSmaha**
Hi,

I add a new parameter to choose if the popup will be show at top on phone.

### CODE REVIEW

**Comment by matos-hayrapetyan** [comment]
@GuillaumeSmaha Thank you for helping us to improve the project.
feel free to hit us if you find something in the future. 
We will appreciate that a lot.

**Comment by GuillaumeSmaha** [comment]
@matos-hayrapetyan You're welcome.
What do you think about this ?

**Comment by matos-hayrapetyan** [comment]
@GuillaumeSmaha sorry for late reply, didn't get any notification about your comment. The code is great . I surely will inject it into the plugin during the next update; yeah ahead of this we have to add an option first,  into general options page to let users change the value.

**Comment by GuillaumeSmaha** [comment]
Ok thanks for the reply. I wait for the next update.

**Pull request merged**
